export const baseUrl='https://api.themoviedb.org/3/';
export const API_KEY="7b5db1d4fd5cc6492f49c469568653fd";
export const imageUrl='https://image.tmdb.org/t/p/original'
export const trending=`trending/all/week?api_key=${API_KEY}&language=en-US`
export const original=`discover/tv?api_key=${API_KEY}&with_networks=213`
export const action=`discover/movie?api_key=${API_KEY}&with_genres=28`
export const comedy=`discover/movie?api_key=${API_KEY}&with_genres=35`
export const horror=`discover/movie?api_key=${API_KEY}&with_genres=27`
export const romance=`discover/movie?api_key=${API_KEY}&with_genres=10749`
export const playing=`movie/now_playing?api_key=${API_KEY}&language=en-US&page=1`
export const upcoming=`movie/upcoming?api_key=${API_KEY}&language=en-US&page=1`
